spring:
  datasource:
    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 10
  profiles:
    active: production
logging:
  level:
    org.springframework: INFO

server:
  port: ${PORT:5000}
